name: Cypress CI

on:
  push:
    branches:
      - testes 

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start backend server
        run: |
          # Navega para a pasta do backend
          cd server 

          # Instala as dependências do backend
          npm install

          # Compila o TypeScript do backend
          npm run compile

          # Inicia o servidor compilado em segundo plano
          npm run serve & 

          # Espera o servidor estar pronto (responde com 200)
          until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)" == "200" ]; do
            echo "Waiting for backend server to start..."
            sleep 1
          done
          echo "Backend server is running successfully."
        shell: /usr/bin/bash -e {0} 

      - name: Install Cypress dependencies (se seu cypress/package.json for separado)
 
        run: |
          # Se o Cypress usa o package.json na raiz, use:
          # npm install
          # Se o Cypress tem seu próprio package.json dentro de 'cypress/', use:
          # cd cypress && npm install && cd ..
          # Por enquanto, vamos assumir que as dependências principais estão na raiz ou já foram instaladas.
          # Se o cypress é na raiz:
          npm install 
       

      - name: Run Cypress tests
        run: npx cypress run 
        env:
          CYPRESS_BASE_URL: http://localhost:8080
         
