name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: [1, 2]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Start Server BackEnd
        run: |
          cd server
          npm install
          npm run start &
          until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)" == "200" ]; do
            echo "Waiting for backend to start..."
            sleep 1
          done
          echo "Backend is running."

      - name: Start Web App FrontEnd
        run: |
          cd web
          npm install
          npm run start &
          until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)" == "200" ]; do
            echo "Waiting for frontend to start..."
            sleep 1
          done
          echo "Frontend is running."

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.mjs
          wait-on: 'http://localhost:3000,http://localhost:8080'
          record: true
          parallel: true
          group: 'Cypress Tests'
          wait-on-timeout: 60

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

