name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Start Server BackEnd
        run: |
          cd server
          npm install
          npm run start &
          until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)" == "200" ]; do
            echo "Waiting for backend to start..."
            sleep 1
          done
          echo "Backend is running."

      - name: Start Web App FrontEnd
        run: |
          cd web
          npm install
          npm run start &
          until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)" == "200" ]; do
            echo "Waiting for frontend to start..."
            sleep 1
          done
          echo "Frontend is running."

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.js
          wait-on: 'http://localhost:3000,http://localhost:8080'
          wait-on-timeout: 60
          spec: |
            cypress/e2e/cadastro-sucesso.cy.js
            cypress/e2e/login-clinica.cy.js
            cypress/e2e/dashboard.cy.js